FROM node:6.4.0

RUN mkdir -p /usr/share/node && cd /usr/share/nginx/html/ && git clone https://github.com/andyhughes/LPMCserver

EXPOSE 3000

# docker run -d --name LPMCserver -p 3000:3000 -v /Users/andrew/Documents/LegalPMC/nodeserver:/usr/share/nginx/html node:6.4.0
# docker exec -it LPMCserver /bin/bash
